# 数据源配置
datasource:
  url: jdbc:mysql://3.140.253.63:3306/bbbus?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=America/New_York
  username: root
  password: Busline#2023


system:
  # entity vo父类路径
  superEntityClass: com.bbbus.common.core.domain.BaseEntity
  # 公用字段 不会生成实体属性
  uperEntityColumns: create_time,create_by_id,update_time,update_by_id


gencode:
  # 作者
  author: Jianbin Shi
  # 项目本地路径 绝对路径   到项目的目录就好了
  # outputUrl: /Users/xbb/soft/aiya/aiya-busline
  outputUrl: F:\aiya\project\generator-plus\src\main\java\cn\xiaobinbin/domain
  # 包名
  # packageName: us.aiya.busline
  packageName: com.bbbus.dao.operator
  # 表名 多个用逗号分隔
  inTables: bbbus_car_order,bbbus_car_order_pay,bbbus_car_order_station,bbbus_car_order_team