# 数据源配置
datasource:
  url: jdbc:mysql://18.222.222.223:3306/aiya-reservation?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=America/New_York
  username: root
  password: KPnCiPh-2700


system:
  # entity vo父类路径
  superEntityClass: us.aiya.busline.utils.BaseEntity
  # 公用字段 不会生成实体属性
  uperEntityColumns: create_time,update_time


gencode:
  # 作者
  author: sain
  # 项目本地路径
  # outputUrl: /Users/xbb/soft/aiya/aiya-busline
  outputUrl: /Users/xbb/soft/aiya/project/aiya-online/reservation
  # 包名
  # packageName: us.aiya.busline
  packageName: us.aiya.reservation
  # 表名 多个用逗号分隔
  inTables: rsv_order

